-- 
-- UV-SENSE COMPREHENSIVE SUPABASE SCHEMA (V3.1 - PERMISSION FIXED)
-- Optimized for Many-to-Many Skin Type Relationships
--

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--------------------------------------------------------------------------------
-- 1. TABLES
--------------------------------------------------------------------------------

-- Table: tbl_skintype (Centralized skin types)
CREATE TABLE IF NOT EXISTS public.tbl_skintype (
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skintype_name TEXT NOT NULL UNIQUE, -- OILY, DRY, NORMAL, COMBINATION, SENSITIVE
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default skin types
INSERT INTO public.tbl_skintype (skintype_name) VALUES 
('OILY'), ('DRY'), ('NORMAL'), ('COMBINATION'), ('SENSITIVE') 
ON CONFLICT (skintype_name) DO NOTHING;

-- Table: tbl_user
CREATE TABLE IF NOT EXISTS public.tbl_user (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    user_name TEXT,
    user_email TEXT,
    user_contact TEXT,
    user_photo TEXT,
    user_gender TEXT,
    user_status TEXT DEFAULT 'active',
    skintype_id BIGINT REFERENCES public.tbl_skintype(type_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_admin
CREATE TABLE IF NOT EXISTS public.tbl_admin (
    id TEXT PRIMARY KEY, -- Using string ID as seen in admin_registration.dart
    admin_name TEXT,
    admin_email TEXT,
    admin_password TEXT, -- Kept because registration logic uses it, though Auth is preferred
    admin_contact TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_category
CREATE TABLE IF NOT EXISTS public.tbl_category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_level
CREATE TABLE IF NOT EXISTS public.tbl_level (
    level_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_name TEXT NOT NULL,
    level_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_product
CREATE TABLE IF NOT EXISTS public.tbl_product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    product_description TEXT,
    category_id BIGINT REFERENCES public.tbl_category(category_id),
    level_id BIGINT REFERENCES public.tbl_level(level_id),
    price DOUBLE PRECISION,
    photo TEXT,
    spf_rating TEXT,
    sunscreen_type TEXT,
    stock INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_product_skintype (Junction Table for Multi-Skin Type Support)
CREATE TABLE IF NOT EXISTS public.tbl_product_skintype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.tbl_product(product_id) ON DELETE CASCADE,
    skintype_id BIGINT REFERENCES public.tbl_skintype(type_id) ON DELETE CASCADE,
    UNIQUE(product_id, skintype_id)
);

-- Table: tbl_stock (Optional, but kept for legacy)
CREATE TABLE IF NOT EXISTS public.tbl_stock (
    stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.tbl_product(product_id) ON DELETE CASCADE,
    stock_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_booking
CREATE TABLE IF NOT EXISTS public.tbl_booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.tbl_user(user_id) ON DELETE CASCADE,
    booking_status INTEGER DEFAULT 0, 
    booking_amount DOUBLE PRECISION DEFAULT 0,
    booking_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_cart
CREATE TABLE IF NOT EXISTS public.tbl_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES public.tbl_booking(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.tbl_product(product_id) ON DELETE CASCADE,
    cart_quantity INTEGER DEFAULT 1,
    cart_status INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_complaint
CREATE TABLE IF NOT EXISTS public.tbl_complaint (
    complaint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.tbl_user(user_id) ON DELETE CASCADE,
    complaint_title TEXT,
    complaint_content TEXT,
    complaint_reply TEXT,
    complaint_status INTEGER DEFAULT 0,
    complaint_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_dermatologist
CREATE TABLE IF NOT EXISTS public.tbl_dermatologist (
    dermatologist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dermatologist_name TEXT,
    dermatologist_email TEXT,
    dermatologist_contact TEXT,
    dermatologist_address TEXT,
    dermatologist_photo TEXT,
    dermatologist_status TEXT DEFAULT 'accepted',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_uv_log
CREATE TABLE IF NOT EXISTS public.tbl_uv_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.tbl_user(user_id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_name TEXT,
    uv_index DOUBLE PRECISION,
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_subscription_plan
CREATE TABLE IF NOT EXISTS public.tbl_subscription_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name TEXT NOT NULL,
    plan_description TEXT,
    plan_price DOUBLE PRECISION NOT NULL,
    plan_duration INTEGER NOT NULL, -- duration in days
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_user_subscription
CREATE TABLE IF NOT EXISTS public.tbl_user_subscription (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.tbl_user(user_id) ON DELETE CASCADE,
    plan_id BIGINT REFERENCES public.tbl_subscription_plan(plan_id) ON DELETE CASCADE,
    start_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    subscription_status TEXT DEFAULT 'active', -- active, expired, cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_uv_recommendation
CREATE TABLE IF NOT EXISTS public.tbl_uv_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_uv DOUBLE PRECISION NOT NULL,
    max_uv DOUBLE PRECISION NOT NULL,
    skin_profile TEXT NOT NULL, -- e.g. "All", "Fitzpatrick 1-2", "Fitzpatrick 3-4", "OILY" etc.
    sunscreen_spf TEXT,
    sunscreen_type TEXT,
    sunscreen_details TEXT,
    dress_color TEXT,
    dress_type TEXT,
    safety_tips TEXT, -- Comma separated tips
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tbl_chatbot_faq
CREATE TABLE IF NOT EXISTS public.tbl_chatbot_faq (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

--------------------------------------------------------------------------------
-- 2. STORAGE BUCKETS (Permissive)
--------------------------------------------------------------------------------

-- Create buckets using insertion (Common in Supabase SQL editor)
INSERT INTO storage.buckets (id, name, public) 
VALUES 
('product_images', 'product_images', true),
('dermatologist_docs', 'dermatologist_docs', true),
('scanner_input', 'scanner_input', true),
('User', 'User', true) 
ON CONFLICT (id) DO UPDATE SET public = true;

--------------------------------------------------------------------------------
-- 3. PERMISSIVE POLICIES (Targeted to avoid ownership errors)
--------------------------------------------------------------------------------

DO $$ 
DECLARE 
    tbl_name TEXT;
BEGIN
    -- Only loop through tables we just created (starting with 'tbl_')
    FOR tbl_name IN 
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' AND tablename LIKE 'tbl_%'
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl_name);
        EXECUTE format('DROP POLICY IF EXISTS "Global Permissive" ON public.%I', tbl_name);
        EXECUTE format('CREATE POLICY "Global Permissive" ON public.%I FOR ALL USING (true) WITH CHECK (true)', tbl_name);
    END LOOP;
END $$;

-- Storage Policies (Wrapped in EXCEPTION block or simplified)
-- Note: Modifying storage.objects RLS sometimes fails if not superuser, 
-- but policies can usually be added if RLS is already enabled.
DO $$ 
BEGIN
    -- Try to enable RLS on storage.objects (if possible)
    BEGIN
        ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
    EXCEPTION WHEN others THEN
        RAISE NOTICE 'Could not alter storage.objects, it may already be managed or restricted.';
    END;

    -- Create a broad policy for all storage objects
    DROP POLICY IF EXISTS "Global Storage Permissive" ON storage.objects;
    CREATE POLICY "Global Storage Permissive" ON storage.objects FOR ALL USING (true) WITH CHECK (true);
END $$;

--------------------------------------------------------------------------------
-- 4. PERMISSIONS (Targeted to avoid ownership errors)
--------------------------------------------------------------------------------

-- Grant permissions ONLY on the tables we created
DO $$ 
DECLARE 
    tbl_name TEXT;
BEGIN
    FOR tbl_name IN 
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' AND tablename LIKE 'tbl_%'
    LOOP
        EXECUTE format('GRANT ALL ON TABLE public.%I TO postgres, anon, authenticated, service_role', tbl_name);
    END LOOP;
END $$;

-- Grant on sequences (usually fine as they are own by the tables)
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

